# Generated by Django 5.2.3 on 2025-07-01 07:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produtor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização do registro.",
                    ),
                ),
                (
                    "documento",
                    models.CharField(
                        help_text="CPF (11 dígitos) ou CNPJ (14 dígitos). Somente números, ou com máscara.",
                        max_length=18,
                        unique=True,
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[("CPF", "CPF"), ("CNPJ", "CNPJ")],
                        help_text="Tipo de documento (CPF ou CNPJ), inferido automaticamente.",
                        max_length=4,
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome completo do produtor ou razão social da empresa.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Produtor Rural",
                "verbose_name_plural": "Produtores Rurais",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Propriedade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização do registro.",
                    ),
                ),
                (
                    "cep",
                    models.CharField(
                        blank=True,
                        help_text="CEP da propriedade (opcional).",
                        max_length=9,
                        null=True,
                    ),
                ),
                (
                    "logradouro",
                    models.CharField(
                        blank=True,
                        help_text="Rua, avenida, estrada etc. (opcional).",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        help_text="Número do imóvel (opcional).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "complemento",
                    models.CharField(
                        blank=True,
                        help_text="Complemento do endereço (ex: Lote 12, Fundos) (opcional).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "bairro",
                    models.CharField(
                        blank=True,
                        help_text="Bairro onde a Propriedade está localizada (opcional).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "cidade",
                    models.CharField(
                        help_text="Cidade onde a Propriedade está localizada.",
                        max_length=100,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        help_text="Sigla do estado (UF) onde a Propriedade está localizada.",
                        max_length=2,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitude da propriedade (ex: -23.55052).",
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitude da propriedade (ex: -46.63330).",
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "nome_propriedade",
                    models.CharField(
                        help_text="Nome da Propriedade ou propriedade rural.",
                        max_length=255,
                    ),
                ),
                (
                    "tipo_atividade",
                    models.CharField(
                        choices=[
                            ("AGRICULTURA", "Agricultura"),
                            ("PECUARIA", "Pecuária"),
                            ("AGROPECUARIA", "Agropecuária"),
                            ("OUTRO", "Outro"),
                        ],
                        default="AGROPECUARIA",
                        help_text="Principal tipo de atividade da Propriedade.",
                        max_length=20,
                    ),
                ),
                (
                    "area_total_hectares",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Área total da Propriedade em hectares.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "area_agricultavel_hectares",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Área em hectares que pode ser usada para plantio.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "area_vegetacao_hectares",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Área em hectares com vegetação nativa ou preservação.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "produtor",
                    models.ForeignKey(
                        help_text="Produtor rural responsável por esta Propriedade.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="propriedades",
                        to="produtores.produtor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Propriedade",
                "verbose_name_plural": "Propriedades",
                "ordering": ["nome_propriedade"],
                "unique_together": {("produtor", "nome_propriedade")},
            },
        ),
        migrations.CreateModel(
            name="Safra",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização do registro.",
                    ),
                ),
                ("ano", models.IntegerField(help_text="Ano da safra (ex: 2023).")),
                (
                    "data_inicio",
                    models.DateField(
                        blank=True,
                        help_text="Data de início da safra (dia/mês/ano).",
                        null=True,
                    ),
                ),
                (
                    "data_fim",
                    models.DateField(
                        blank=True,
                        help_text="Data de fim da safra (dia/mês/ano).",
                        null=True,
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True,
                        help_text="Descrição opcional da safra (ex: Safra de Verão).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "propriedade",
                    models.ForeignKey(
                        help_text="Propriedade onde esta safra foi cultivada.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safras",
                        to="produtores.propriedade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Safra",
                "verbose_name_plural": "Safras",
                "ordering": ["-ano"],
                "unique_together": {("propriedade", "ano")},
            },
        ),
        migrations.CreateModel(
            name="AtividadeRural",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização do registro.",
                    ),
                ),
                (
                    "nome_cultura",
                    models.CharField(
                        help_text="Nome da cultura plantada (ex: Soja, Milho, Café).",
                        max_length=100,
                    ),
                ),
                (
                    "area_plantada_hectares",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Área específica em hectares que esta cultura ocupou nesta safra (opcional).",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "data_plantio",
                    models.DateField(
                        blank=True,
                        help_text="Data em que a cultura foi plantada (opcional).",
                        null=True,
                    ),
                ),
                (
                    "data_colheita",
                    models.DateField(
                        blank=True,
                        help_text="Data em que a cultura foi colhida (opcional).",
                        null=True,
                    ),
                ),
                (
                    "safra",
                    models.ForeignKey(
                        help_text="Safra à qual esta cultura pertence.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="culturas_plantadas",
                        to="produtores.safra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cultura Plantada",
                "verbose_name_plural": "Culturas Plantadas",
                "ordering": ["nome_cultura"],
                "unique_together": {("safra", "nome_cultura")},
            },
        ),
    ]
