# Generated by Django 5.2.4 on 2025-07-04 03:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Propriedade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização do registro.",
                    ),
                ),
                (
                    "nome_propriedade",
                    models.CharField(
                        help_text="Nome da Propriedade ou propriedade rural.",
                        max_length=255,
                    ),
                ),
                (
                    "tipo_atividade",
                    models.CharField(
                        choices=[
                            ("AGRICULTURA", "Agricultura"),
                            ("PECUARIA", "Pecuária"),
                            ("AGROPECUARIA", "Agropecuária"),
                            ("OUTRO", "Outro"),
                        ],
                        default="AGROPECUARIA",
                        help_text="Principal tipo de atividade da Propriedade.",
                        max_length=20,
                    ),
                ),
                (
                    "area_total_hectares",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Área total da Propriedade em hectares.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "area_agricultavel_hectares",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Área em hectares que pode ser usada para plantio.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "area_vegetacao_hectares",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Área em hectares com vegetação nativa ou preservação.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "endereco",
                    models.OneToOneField(
                        blank=True,
                        help_text="Endereço da propriedade.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.endereco",
                    ),
                ),
                (
                    "produtor",
                    models.ForeignKey(
                        help_text="Produtor rural responsável por esta Propriedade.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="propriedades",
                        to="core.produtorrural",
                    ),
                ),
            ],
            options={
                "verbose_name": "Propriedade",
                "verbose_name_plural": "Propriedades",
                "ordering": ["nome_propriedade"],
                "unique_together": {("produtor", "nome_propriedade")},
            },
        ),
        migrations.CreateModel(
            name="Safra",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização do registro.",
                    ),
                ),
                ("ano", models.IntegerField(help_text="Ano da safra (ex: 2023).")),
                (
                    "data_inicio",
                    models.DateField(
                        blank=True,
                        help_text="Data de início da safra (dia/mês/ano).",
                        null=True,
                    ),
                ),
                (
                    "data_fim",
                    models.DateField(
                        blank=True,
                        help_text="Data de fim da safra (dia/mês/ano).",
                        null=True,
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True,
                        help_text="Descrição opcional da safra (ex: Safra de Verão).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "propriedade",
                    models.ForeignKey(
                        help_text="Propriedade onde esta safra foi cultivada.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safras",
                        to="produtores.propriedade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Safra",
                "verbose_name_plural": "Safras",
                "ordering": ["-ano"],
                "unique_together": {("propriedade", "ano")},
            },
        ),
        migrations.CreateModel(
            name="AtividadeRural",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização do registro.",
                    ),
                ),
                (
                    "nome_cultura",
                    models.CharField(
                        help_text="Nome da cultura plantada (ex: Soja, Milho, Café).",
                        max_length=100,
                    ),
                ),
                (
                    "area_plantada_hectares",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Área específica em hectares que esta cultura ocupou nesta safra (opcional).",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "data_plantio",
                    models.DateField(
                        blank=True,
                        help_text="Data em que a cultura foi plantada (opcional).",
                        null=True,
                    ),
                ),
                (
                    "data_colheita",
                    models.DateField(
                        blank=True,
                        help_text="Data em que a cultura foi colhida (opcional).",
                        null=True,
                    ),
                ),
                (
                    "safra",
                    models.ForeignKey(
                        help_text="Safra à qual esta cultura pertence.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="culturas_plantadas",
                        to="produtores.safra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cultura Plantada",
                "verbose_name_plural": "Culturas Plantadas",
                "ordering": ["nome_cultura"],
                "unique_together": {("safra", "nome_cultura")},
            },
        ),
    ]
