services:
  
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: "techagro_user"
      POSTGRES_PASSWORD: "changeme"
      POSTGRES_DB: "techagro_db"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python framework/manage.py migrate &&
             python framework/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    restart: always
    volumes:
      - ./docker/pgadmin_connection.json:/pgadmin4/servers.json

volumes:
  pgdata:
