# fly.toml app configuration file generated for techagro on 2025-07-01T14:35:39-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'techagro'
primary_region = 'gig'
console_command = '/code/manage.py shell'

[build]

[deploy]
release_command = "/bin/sh -c \"python manage.py migrate --noinput && python manage.py popular_mock && python manage.py collectstatic --noinput\""

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/static'
  url_prefix = '/static/'
