site_name: Tech Agro - Desafio 

theme:
  name: readthedocs
  locale: pt

nav:
  - Do Desafio: desafio.md
  - Executar via Docker: ExecDocker.md
  - Executar via Python: ExecLocal.md
  - Exemplo de Dados: playload.md
  - Sobre: sobre.md
  - Licenca: license.md
  