site_name: Tech Agro 

theme:
  name: material
  nav_style: dark 
  locale: pt_BR


plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          show_source: true

nav:
  - Do Desafio: desafio.md
  - Executar via Docker: ExecDocker.md
  - Executar via Python: ExecLocal.md
  - Exemplo de Dados: playload.md
  - Sobre: sobre.md
  - Licenca: license.md
  