# Generated by Django 5.2.4 on 2025-07-04 03:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgenteEscritorio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização do registro.",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome completo ou Razão Social.", max_length=255
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Endereço de e-mail.", max_length=255, unique=True
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True,
                        help_text="Número de telefone para contato.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "departamento",
                    models.CharField(
                        blank=True,
                        help_text="Departamento do agente de escritório.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Usuário associado a este Agente de Escritório.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agente_escritorio",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agente de Escritório",
                "verbose_name_plural": "Agentes de Escritório",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="TecnicoAgrícola",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização do registro.",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome completo ou Razão Social.", max_length=255
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Endereço de e-mail.", max_length=255, unique=True
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True,
                        help_text="Número de telefone para contato.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "registro_profissional",
                    models.CharField(
                        blank=True,
                        help_text="Número de registro profissional do técnico (ex: CREA, CRMV).",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Usuário associado a este Técnico Agrícola.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tecnico_agricola",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Técnico Agrícola",
                "verbose_name_plural": "Técnicos Agrícolas",
                "ordering": ["nome"],
            },
        ),
    ]
