name: "PROD DEPLOY"

on:
  push:
    branches:
      - main

# Conforme docs da AWS - nivel de permissoes de trabalho do workflow (ASSUME-ROLE)
permissions:
  id-token: write
  contents: read


jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: prod
      aws-assume-role-arn: "arn:aws:iam::104976232069:role/github-action-edcastanha-pipeline"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "edcastanha-sa-east-1-statefile"
      aws-lock-dynamodb-table: "edcastanha-sa-east-1-terraform-lock"